from telegram import Update
from telegram.ext import ContextTypes

from handlers.deliver import deliver_file
from services.user_service import save_user
from utils.helpers import get_target_message

from handlers.channel import user_in_channels, build_join_keyboard, set_pending_file

async def start_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    message = get_target_message(update)
    if not message or not update.effective_user:
        return

    user = update.effective_user
    await save_user(user.id, user.username, user.first_name)

    if context.args:
        # Check if user is in all required channels
        is_member = await user_in_channels(context, user.id)
        if not is_member:
            # Save pending file — deliver after join request
            set_pending_file(user.id, context.args[0])
            await message.reply_text(
                "❌ Pehle channel join karo ya join request bhejo!\n\nRequest bhejne ke baad file link dobara click karo:",
                reply_markup=build_join_keyboard(context.args[0]),
            )
            return

        await deliver_file(update, context, context.args[0])
        return

    bot_role = context.application.bot_data.get("role", "primary") if context.application else "primary"
    if bot_role == "secondary":
        await message.reply_text("🔗 This bot only works with file links generated by the main bot.")
        return

    await message.reply_text("🔒 Send me a file to lock it! (Admin only)")
