from telegram import Update
from telegram.ext import ContextTypes

from handlers.deliver import deliver_file
from services.user_service import save_user
from utils.helpers import get_target_message

from config import REQUIRED_CHANNELS
from handlers.channel import user_in_required_channels, build_join_keyboard_for_required_channels

async def start_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    message = get_target_message(update)
    if not message or not update.effective_user:
        return

    user = update.effective_user
    await save_user(user.id, user.username, user.first_name)

    if context.args:
        bot_role = context.application.bot_data.get("role", "primary") if context.application else "primary"
        
        # For secondary bot (BOT_TOKEN1), check channel membership if channels are required
        if bot_role == "secondary" and REQUIRED_CHANNELS:
            is_member = await user_in_required_channels(context, user.id)
            if not is_member:
                await message.reply_text(
                    "❌ You need to join the required channel(s) to access this file.\n\nPlease join first and then try again:",
                    reply_markup=build_join_keyboard_for_required_channels(context.args[0]),
                )
                return
        
        await deliver_file(update, context, context.args[0])
        return

    bot_role = context.application.bot_data.get("role", "primary") if context.application else "primary"
    if bot_role == "secondary":
        await message.reply_text("🔗 This bot only works with file links generated by the main bot.")
        return

    await message.reply_text("🔒 Send me a file to lock it! (Admin only)")
